// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['apps']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function GetSoftwareList() {
  return window['go']['apps']['App']['GetSoftwareList']();
}

export function GetSysInfo() {
  return window['go']['apps']['App']['GetSysInfo']();
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['apps']['App']['OnSecondInstanceLaunch'](arg1);
}

export function RestartSystem(arg1) {
  return window['go']['apps']['App']['RestartSystem'](arg1);
}

export function SelectByID(arg1) {
  return window['go']['apps']['App']['SelectByID'](arg1);
}

export function SelectByName(arg1) {
  return window['go']['apps']['App']['SelectByName'](arg1);
}

export function SelectClassify() {
  return window['go']['apps']['App']['SelectClassify']();
}

export function SelectPage(arg1, arg2, arg3) {
  return window['go']['apps']['App']['SelectPage'](arg1, arg2, arg3);
}

export function UninstallSoftware(arg1) {
  return window['go']['apps']['App']['UninstallSoftware'](arg1);
}

export function UpdateApp() {
  return window['go']['apps']['App']['UpdateApp']();
}
