// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectDelete(arg1) {
  return window['go']['apps']['App']['CollectDelete'](arg1);
}

export function CollectInsert(arg1) {
  return window['go']['apps']['App']['CollectInsert'](arg1);
}

export function CollectSelectAll() {
  return window['go']['apps']['App']['CollectSelectAll']();
}

export function CollectUpdate(arg1) {
  return window['go']['apps']['App']['CollectUpdate'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['apps']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function GetDatabaseVersion() {
  return window['go']['apps']['App']['GetDatabaseVersion']();
}

export function GetNewDataBaseVersion() {
  return window['go']['apps']['App']['GetNewDataBaseVersion']();
}

export function GetSoftwareList() {
  return window['go']['apps']['App']['GetSoftwareList']();
}

export function GetSysInfo() {
  return window['go']['apps']['App']['GetSysInfo']();
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['apps']['App']['OnSecondInstanceLaunch'](arg1);
}

export function RestartSystem(arg1) {
  return window['go']['apps']['App']['RestartSystem'](arg1);
}

export function SelectByID(arg1) {
  return window['go']['apps']['App']['SelectByID'](arg1);
}

export function SelectByName(arg1) {
  return window['go']['apps']['App']['SelectByName'](arg1);
}

export function SelectClassify() {
  return window['go']['apps']['App']['SelectClassify']();
}

export function SelectPage(arg1, arg2, arg3) {
  return window['go']['apps']['App']['SelectPage'](arg1, arg2, arg3);
}

export function UninstallSoftware(arg1) {
  return window['go']['apps']['App']['UninstallSoftware'](arg1);
}

export function UpdateApp() {
  return window['go']['apps']['App']['UpdateApp']();
}

export function UpdateDatabase() {
  return window['go']['apps']['App']['UpdateDatabase']();
}
