// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';
import {model} from '../models';

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function SelectByID(arg1:string):Promise<model.BaseModel>;

export function SelectByName(arg1:string):Promise<model.BaseModel>;

export function SelectPage(arg1:number,arg2:number,arg3:string):Promise<model.BaseModel>;
