// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['apps']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['apps']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SelectByID(arg1) {
  return window['go']['apps']['App']['SelectByID'](arg1);
}

export function SelectPage(arg1, arg2, arg3) {
  return window['go']['apps']['App']['SelectPage'](arg1, arg2, arg3);
}
